apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reminder-cron
  namespace: default
spec:
  type: bindings.cron
  version: v1
  metadata:
    # Check for due reminders every 5 minutes
    - name: schedule
      value: "*/5 * * * *"
    - name: direction
      value: "input"
