apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.postgresql
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: todo-secrets
        key: database-url
    - name: tableName
      value: "dapr_state"
    - name: keyPrefix
      value: "none"
    # Actor state table
    - name: actorStateStore
      value: "true"
