apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: reminders-sub
spec:
  pubsubname: kafka-pubsub
  topic: reminders
  routes:
    default: /events/reminder
  scopes:
    - notification-service
