apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: task-updates-sub
spec:
  pubsubname: kafka-pubsub
  topic: task-updates
  routes:
    default: /events/task-update
  scopes:
    - websocket-service
