apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: task-events-sub
spec:
  pubsubname: kafka-pubsub
  topic: task-events
  routes:
    default: /events/task
  scopes:
    - todo-backend
    - audit-service
    - recurring-service
